// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'color.dart';
import 'curve.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StepDirection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`

/// Result of processing an action (legacy).
class ActionResultDto {
  /// The lighting values to apply (None if lights should be off)
  final LightingValuesDto? lighting;

  /// Updated room state after the action
  final RoomStateDto newState;

  /// Whether lights should be turned off
  final bool shouldTurnOff;

  /// Whether lights should be turned on
  final bool shouldTurnOn;

  /// Whether state changed (for persistence)
  final bool stateChanged;

  const ActionResultDto({
    this.lighting,
    required this.newState,
    required this.shouldTurnOff,
    required this.shouldTurnOn,
    required this.stateChanged,
  });

  @override
  int get hashCode =>
      lighting.hashCode ^
      newState.hashCode ^
      shouldTurnOff.hashCode ^
      shouldTurnOn.hashCode ^
      stateChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActionResultDto &&
          runtimeType == other.runtimeType &&
          lighting == other.lighting &&
          newState == other.newState &&
          shouldTurnOff == other.shouldTurnOff &&
          shouldTurnOn == other.shouldTurnOn &&
          stateChanged == other.stateChanged;
}

/// Room state for calculating action results (legacy).
class RoomStateDto {
  /// Whether rhythm mode is enabled for this room
  final bool rhythmEnabled;

  /// Whether lights are currently on
  final bool lightsOn;

  /// Current time offset in minutes (from stepping)
  final double timeOffsetMinutes;

  /// Brightness offset (from dim up/down, -100 to 100)
  final double brightnessOffset;

  const RoomStateDto({
    required this.rhythmEnabled,
    required this.lightsOn,
    required this.timeOffsetMinutes,
    required this.brightnessOffset,
  });

  static RoomStateDto default_() =>
      RustLib.instance.api.crateApiDtoActionRoomStateDtoDefault();

  @override
  int get hashCode =>
      rhythmEnabled.hashCode ^
      lightsOn.hashCode ^
      timeOffsetMinutes.hashCode ^
      brightnessOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomStateDto &&
          runtimeType == other.runtimeType &&
          rhythmEnabled == other.rhythmEnabled &&
          lightsOn == other.lightsOn &&
          timeOffsetMinutes == other.timeOffsetMinutes &&
          brightnessOffset == other.brightnessOffset;
}
