// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'color.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'solar.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Curve configuration DTO for Flutter.
///
/// Maps to `CurveConfig` in Flutter's `config_model.dart`.
/// Uses super-Gaussian (flat-topped bell curve) parameters.
class CurveConfigDto {
  final int minColorTemp;
  final int maxColorTemp;
  final int minBrightness;
  final int maxBrightness;

  /// Morning ramp speed for brightness (<1 = faster, >1 = slower)
  final double widthLeftBri;

  /// Evening ramp speed for brightness (<1 = faster, >1 = slower)
  final double widthRightBri;

  /// Morning ramp speed for CCT (<1 = faster, >1 = slower)
  final double widthLeftCct;

  /// Evening ramp speed for CCT (<1 = faster, >1 = slower)
  final double widthRightCct;

  /// Shape exponent for super-Gaussian curve (2 = round, 6 = flat plateau)
  final double shapeP;
  final int maxDimSteps;

  /// Light transition fade duration in milliseconds (default 500).
  final int fadeMs;

  /// Default motion timeout in seconds (default 600 = 10 minutes).
  final int motionTimeoutSecs;

  const CurveConfigDto({
    required this.minColorTemp,
    required this.maxColorTemp,
    required this.minBrightness,
    required this.maxBrightness,
    required this.widthLeftBri,
    required this.widthRightBri,
    required this.widthLeftCct,
    required this.widthRightCct,
    required this.shapeP,
    required this.maxDimSteps,
    required this.fadeMs,
    required this.motionTimeoutSecs,
  });

  static CurveConfigDto default_() =>
      RustLib.instance.api.crateApiDtoCurveCurveConfigDtoDefault();

  @override
  int get hashCode =>
      minColorTemp.hashCode ^
      maxColorTemp.hashCode ^
      minBrightness.hashCode ^
      maxBrightness.hashCode ^
      widthLeftBri.hashCode ^
      widthRightBri.hashCode ^
      widthLeftCct.hashCode ^
      widthRightCct.hashCode ^
      shapeP.hashCode ^
      maxDimSteps.hashCode ^
      fadeMs.hashCode ^
      motionTimeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurveConfigDto &&
          runtimeType == other.runtimeType &&
          minColorTemp == other.minColorTemp &&
          maxColorTemp == other.maxColorTemp &&
          minBrightness == other.minBrightness &&
          maxBrightness == other.maxBrightness &&
          widthLeftBri == other.widthLeftBri &&
          widthRightBri == other.widthRightBri &&
          widthLeftCct == other.widthLeftCct &&
          widthRightCct == other.widthRightCct &&
          shapeP == other.shapeP &&
          maxDimSteps == other.maxDimSteps &&
          fadeMs == other.fadeMs &&
          motionTimeoutSecs == other.motionTimeoutSecs;
}

/// Curve data for visualization.
///
/// Maps to `CurveData` in Flutter's `rhythm_api.dart`.
class CurveDataDto {
  final Float64List hours;
  final Int32List brightness;
  final Int32List kelvin;
  final SolarInfoDto solar;

  const CurveDataDto({
    required this.hours,
    required this.brightness,
    required this.kelvin,
    required this.solar,
  });

  @override
  int get hashCode =>
      hours.hashCode ^ brightness.hashCode ^ kelvin.hashCode ^ solar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurveDataDto &&
          runtimeType == other.runtimeType &&
          hours == other.hours &&
          brightness == other.brightness &&
          kelvin == other.kelvin &&
          solar == other.solar;
}

/// Lighting values at a specific time.
class LightingValuesDto {
  final int kelvin;

  /// Color temperature in mireds (micro reciprocal degrees).
  /// Calculated as 1,000,000 / kelvin. Used by Hue bulbs (ct parameter).
  final int mireds;
  final int brightness;
  final RgbDto rgb;
  final XyDto xy;
  final double solarTime;
  final double sunPosition;

  const LightingValuesDto({
    required this.kelvin,
    required this.mireds,
    required this.brightness,
    required this.rgb,
    required this.xy,
    required this.solarTime,
    required this.sunPosition,
  });

  @override
  int get hashCode =>
      kelvin.hashCode ^
      mireds.hashCode ^
      brightness.hashCode ^
      rgb.hashCode ^
      xy.hashCode ^
      solarTime.hashCode ^
      sunPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightingValuesDto &&
          runtimeType == other.runtimeType &&
          kelvin == other.kelvin &&
          mireds == other.mireds &&
          brightness == other.brightness &&
          rgb == other.rgb &&
          xy == other.xy &&
          solarTime == other.solarTime &&
          sunPosition == other.sunPosition;
}

/// A single step point for visualization.
class StepPointDto {
  final double hour;
  final int brightness;
  final int kelvin;
  final Int32List rgb;

  const StepPointDto({
    required this.hour,
    required this.brightness,
    required this.kelvin,
    required this.rgb,
  });

  @override
  int get hashCode =>
      hour.hashCode ^ brightness.hashCode ^ kelvin.hashCode ^ rgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepPointDto &&
          runtimeType == other.runtimeType &&
          hour == other.hour &&
          brightness == other.brightness &&
          kelvin == other.kelvin &&
          rgb == other.rgb;
}

/// Step sequences for dimming visualization.
class StepSequencesDto {
  final List<StepPointDto> stepUp;
  final List<StepPointDto> stepDown;

  const StepSequencesDto({
    required this.stepUp,
    required this.stepDown,
  });

  @override
  int get hashCode => stepUp.hashCode ^ stepDown.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepSequencesDto &&
          runtimeType == other.runtimeType &&
          stepUp == other.stepUp &&
          stepDown == other.stepDown;
}
