// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Hue V2 API button event types for FFI.
///
/// These map directly to the `last_event` field in Hue V2 button resources
/// from the SSE event stream.
enum HueButtonEventTypeDto {
  /// Button was initially pressed down.
  initialPress,

  /// Button is being held down (repeat events).
  repeat,

  /// Button released after a short press.
  shortRelease,

  /// Button released after a long press.
  longRelease,

  /// Button has been held for an extended time.
  longPress,
  ;

  /// Parse from Hue V2 API string value.
  ///
  /// Returns `None` for unknown values.
  static HueButtonEventTypeDto? fromApiValue({required String value}) =>
      RustLib.instance.api
          .crateApiDtoHueHueButtonEventTypeDtoFromApiValue(value: value);
}
