// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// A single behavior to device mapping.
class BehaviorMappingDto {
  /// The behavior_instance resource ID.
  final String behaviorId;

  /// The device resource ID this behavior configures.
  final String deviceId;

  const BehaviorMappingDto({
    required this.behaviorId,
    required this.deviceId,
  });

  @override
  int get hashCode => behaviorId.hashCode ^ deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BehaviorMappingDto &&
          runtimeType == other.runtimeType &&
          behaviorId == other.behaviorId &&
          deviceId == other.deviceId;
}

/// Result of removing a behavior.
class BehaviorRemoveResultDto {
  /// The updated tracker state.
  final HueBehaviorTrackerDto tracker;

  /// True if a device was unconfigured (no more behaviors reference it).
  final bool deviceUnconfigured;

  const BehaviorRemoveResultDto({
    required this.tracker,
    required this.deviceUnconfigured,
  });

  @override
  int get hashCode => tracker.hashCode ^ deviceUnconfigured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BehaviorRemoveResultDto &&
          runtimeType == other.runtimeType &&
          tracker == other.tracker &&
          deviceUnconfigured == other.deviceUnconfigured;
}

/// DTO for HueBehaviorTracker state.
///
/// Uses Vec instead of HashMap/HashSet for FFI compatibility.
class HueBehaviorTrackerDto {
  /// Behavior ID to device ID mappings as (behavior_id, device_id) tuples.
  final List<BehaviorMappingDto> behaviorMappings;

  /// Device IDs that have at least one behavior_instance.
  final List<String> configuredDeviceIds;

  const HueBehaviorTrackerDto({
    required this.behaviorMappings,
    required this.configuredDeviceIds,
  });

  static HueBehaviorTrackerDto default_() =>
      RustLib.instance.api.crateApiDtoHueRegistryHueBehaviorTrackerDtoDefault();

  @override
  int get hashCode => behaviorMappings.hashCode ^ configuredDeviceIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HueBehaviorTrackerDto &&
          runtimeType == other.runtimeType &&
          behaviorMappings == other.behaviorMappings &&
          configuredDeviceIds == other.configuredDeviceIds;
}

/// DTO for a Hue button.
class HueButtonDto {
  /// V2 resource ID of the button.
  final String id;

  /// Control ID (button index, 1-4 for dimmer switch).
  final int controlId;

  /// Owner device resource ID.
  final String ownerDeviceId;

  const HueButtonDto({
    required this.id,
    required this.controlId,
    required this.ownerDeviceId,
  });

  @override
  int get hashCode => id.hashCode ^ controlId.hashCode ^ ownerDeviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HueButtonDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          controlId == other.controlId &&
          ownerDeviceId == other.ownerDeviceId;
}

/// DTO for a Hue room.
class HueRoomDto {
  /// V2 resource ID.
  final String id;

  /// Human-readable name.
  final String name;

  const HueRoomDto({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HueRoomDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// DTO for a Hue switch device.
class HueSwitchDeviceDto {
  /// V2 resource ID of the device.
  final String id;

  /// Human-readable name.
  final String name;

  /// Product name/model (e.g., "Hue dimmer switch").
  final String? productName;

  /// List of button service IDs belonging to this device.
  final List<String> buttonIds;

  /// V2 resource ID of the room this device is assigned to.
  final String? roomId;

  const HueSwitchDeviceDto({
    required this.id,
    required this.name,
    this.productName,
    required this.buttonIds,
    this.roomId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      productName.hashCode ^
      buttonIds.hashCode ^
      roomId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HueSwitchDeviceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          productName == other.productName &&
          buttonIds == other.buttonIds &&
          roomId == other.roomId;
}
