// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'curve.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A command to send to a light device.
class LightCommandDto {
  /// The device ID to control.
  final String deviceId;

  /// The room this device belongs to.
  final String roomId;

  /// The command type.
  final LightCommandType commandType;

  /// Brightness (0-100), only for TurnOn.
  final int? brightness;

  /// Color temperature in Kelvin, only for TurnOn.
  final int? kelvin;

  const LightCommandDto({
    required this.deviceId,
    required this.roomId,
    required this.commandType,
    this.brightness,
    this.kelvin,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      roomId.hashCode ^
      commandType.hashCode ^
      brightness.hashCode ^
      kelvin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightCommandDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          roomId == other.roomId &&
          commandType == other.commandType &&
          brightness == other.brightness &&
          kelvin == other.kelvin;
}

/// Command type for light control.
enum LightCommandType {
  turnOn,
  turnOff,
  ;
}

/// Action type for rhythm runner.
///
/// Maps to ButtonAction in rhythm-core.
enum RhythmActionDto {
  /// Toggle lights on/off with rhythm mode
  onPress,

  /// Turn off lights
  offPress,

  /// Reset to current time position
  reset,

  /// Step up (brighten and cool) along the curve
  stepUp,

  /// Step down (dim and warm) along the curve
  stepDown,

  /// Enable rhythm mode and turn on
  rhythmOn,

  /// Disable rhythm mode (lights unchanged)
  rhythmOff,

  /// Dim up (brightness only, no color temp change)
  dimUp,

  /// Dim down (brightness only, no color temp change)
  dimDown,
  ;
}

/// A room managed by the runner.
class RoomDto {
  /// Unique identifier for this room.
  final String id;

  /// Human-readable name.
  final String name;

  /// Source/provider for this room.
  final RoomSourceDto source;

  /// Device IDs assigned to this room.
  final List<String> deviceIds;

  /// Whether rhythm mode is enabled.
  final bool rhythmEnabled;

  /// Whether this room is disabled (excluded from kiosk mode).
  final bool disabled;

  /// Whether lights are currently on.
  final bool lightsOn;

  /// Time offset in minutes (from stepping).
  final double timeOffsetMinutes;

  /// Brightness offset (from dim up/down, -100 to 100).
  final double brightnessOffset;

  /// Per-room curve configuration (None uses global config).
  final CurveConfigDto? curveConfig;

  const RoomDto.raw({
    required this.id,
    required this.name,
    required this.source,
    required this.deviceIds,
    required this.rhythmEnabled,
    required this.disabled,
    required this.lightsOn,
    required this.timeOffsetMinutes,
    required this.brightnessOffset,
    this.curveConfig,
  });

  factory RoomDto({required String id, required String name}) =>
      RustLib.instance.api.crateApiDtoRunnerRoomDtoNew(id: id, name: name);

  /// Create a new room with a specified source.
  static RoomDto withSource(
          {required String id,
          required String name,
          required RoomSourceDto source}) =>
      RustLib.instance.api.crateApiDtoRunnerRoomDtoWithSource(
          id: id, name: name, source: source);

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      source.hashCode ^
      deviceIds.hashCode ^
      rhythmEnabled.hashCode ^
      disabled.hashCode ^
      lightsOn.hashCode ^
      timeOffsetMinutes.hashCode ^
      brightnessOffset.hashCode ^
      curveConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          source == other.source &&
          deviceIds == other.deviceIds &&
          rhythmEnabled == other.rhythmEnabled &&
          disabled == other.disabled &&
          lightsOn == other.lightsOn &&
          timeOffsetMinutes == other.timeOffsetMinutes &&
          brightnessOffset == other.brightnessOffset &&
          curveConfig == other.curveConfig;
}

/// Source/provider for a room.
///
/// Identifies where a room was imported from.
enum RoomSourceDto {
  /// Unknown source (backwards compatibility)
  unknown,

  /// Philips Hue bridge
  hue,

  /// Home Assistant via WebSocket
  homeAssistant,

  /// ESP32 standalone controller
  esp32,
  ;
}

/// Result of handling an action.
class RunnerActionResultDto {
  /// Updated runner state.
  final RunnerStateDto state;

  /// Commands to execute.
  final List<LightCommandDto> commands;

  /// Whether state changed (for persistence).
  final bool stateChanged;

  const RunnerActionResultDto({
    required this.state,
    required this.commands,
    required this.stateChanged,
  });

  @override
  int get hashCode =>
      state.hashCode ^ commands.hashCode ^ stateChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunnerActionResultDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          commands == other.commands &&
          stateChanged == other.stateChanged;
}

/// Complete runner state - holds all rooms.
class RunnerStateDto {
  /// All managed rooms.
  final List<RoomDto> rooms;

  const RunnerStateDto({
    required this.rooms,
  });

  static RunnerStateDto default_() =>
      RustLib.instance.api.crateApiDtoRunnerRunnerStateDtoDefault();

  @override
  int get hashCode => rooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunnerStateDto &&
          runtimeType == other.runtimeType &&
          rooms == other.rooms;
}
