// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Action type for rhythm runner button events.
///
/// The app handles room state locally in Dart, but Hue button mapping still
/// returns this enum from Rust.
enum RhythmActionDto {
  /// Toggle lights on/off with rhythm mode
  onPress,

  /// Turn off lights
  offPress,

  /// Reset to current time position
  reset,

  /// Step up (brighten and cool) along the curve
  stepUp,

  /// Step down (dim and warm) along the curve
  stepDown,

  /// Enable rhythm mode and turn on
  rhythmOn,

  /// Disable rhythm mode (lights unchanged)
  rhythmOff,

  /// Dim up (brightness only, no color temp change)
  dimUp,

  /// Dim down (brightness only, no color temp change)
  dimDown,
  ;
}
