// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Solar information DTO.
class SolarInfoDto {
  final double? sunrise;
  final double? sunset;
  final double solarNoon;
  final double solarMidnight;
  final double? dayLength;

  /// Dawn twilight times (before sunrise)
  final TwilightPhaseDto? dawn;

  /// Dusk twilight times (after sunset)
  final TwilightPhaseDto? dusk;

  const SolarInfoDto({
    this.sunrise,
    this.sunset,
    required this.solarNoon,
    required this.solarMidnight,
    this.dayLength,
    this.dawn,
    this.dusk,
  });

  @override
  int get hashCode =>
      sunrise.hashCode ^
      sunset.hashCode ^
      solarNoon.hashCode ^
      solarMidnight.hashCode ^
      dayLength.hashCode ^
      dawn.hashCode ^
      dusk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SolarInfoDto &&
          runtimeType == other.runtimeType &&
          sunrise == other.sunrise &&
          sunset == other.sunset &&
          solarNoon == other.solarNoon &&
          solarMidnight == other.solarMidnight &&
          dayLength == other.dayLength &&
          dawn == other.dawn &&
          dusk == other.dusk;
}

/// Sun times DTO for sunrise/sunset calculations.
class SunTimesDto {
  /// Sunrise time in local decimal hours (0-24)
  final double sunrise;

  /// Sunset time in local decimal hours (0-24)
  final double sunset;

  /// Solar noon in local decimal hours (0-24)
  final double solarNoon;

  /// Solar midnight in local decimal hours (0-24)
  final double solarMidnight;

  /// Day length in hours
  final double dayLength;

  const SunTimesDto({
    required this.sunrise,
    required this.sunset,
    required this.solarNoon,
    required this.solarMidnight,
    required this.dayLength,
  });

  @override
  int get hashCode =>
      sunrise.hashCode ^
      sunset.hashCode ^
      solarNoon.hashCode ^
      solarMidnight.hashCode ^
      dayLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SunTimesDto &&
          runtimeType == other.runtimeType &&
          sunrise == other.sunrise &&
          sunset == other.sunset &&
          solarNoon == other.solarNoon &&
          solarMidnight == other.solarMidnight &&
          dayLength == other.dayLength;
}

/// Twilight phase times DTO for Flutter.
///
/// Times are in local decimal hours (0-24).
/// `None` indicates the event doesn't occur (polar regions).
class TwilightPhaseDto {
  /// Civil twilight: sun 6° below horizon
  final double? civil;

  /// Nautical twilight: sun 12° below horizon
  final double? nautical;

  /// Astronomical twilight: sun 18° below horizon
  final double? astronomical;

  const TwilightPhaseDto({
    this.civil,
    this.nautical,
    this.astronomical,
  });

  @override
  int get hashCode =>
      civil.hashCode ^ nautical.hashCode ^ astronomical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TwilightPhaseDto &&
          runtimeType == other.runtimeType &&
          civil == other.civil &&
          nautical == other.nautical &&
          astronomical == other.astronomical;
}

/// Full twilight times DTO for Flutter.
class TwilightTimesDto {
  /// Dawn twilight times (morning, before sunrise)
  final TwilightPhaseDto dawn;

  /// Dusk twilight times (evening, after sunset)
  final TwilightPhaseDto dusk;

  const TwilightTimesDto({
    required this.dawn,
    required this.dusk,
  });

  @override
  int get hashCode => dawn.hashCode ^ dusk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TwilightTimesDto &&
          runtimeType == other.runtimeType &&
          dawn == other.dawn &&
          dusk == other.dusk;
}
