// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto/color.dart';
import 'dto/curve.dart';
import 'dto/solar.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate curve data for visualization.
///
/// This is the main function for generating the lighting curve graph.
/// It samples the curve at each hour from 0-23 and returns brightness
/// and color temperature values.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `latitude` - Latitude in degrees (for elevation calculations)
/// * `day_of_year` - Day of year (1-365) for seasonal adjustments
///
/// # Returns
///
/// CurveDataDto with hourly brightness and kelvin values.
CurveDataDto generateCurveData(
        {required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear}) =>
    RustLib.instance.api.crateApiCurveGenerateCurveData(
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear);

/// Generate high-resolution curve data for smooth graph rendering.
///
/// Samples the curve at smaller intervals for a smoother graph.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `latitude` - Latitude in degrees
/// * `day_of_year` - Day of year (1-365)
/// * `samples_per_hour` - Number of samples per hour (default: 4)
///
/// # Returns
///
/// CurveDataDto with high-resolution brightness and kelvin values.
CurveDataDto generateCurveDataHighRes(
        {required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear,
        required int samplesPerHour}) =>
    RustLib.instance.api.crateApiCurveGenerateCurveDataHighRes(
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear,
        samplesPerHour: samplesPerHour);

/// Calculate lighting values for a specific hour.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `latitude` - Latitude in degrees
/// * `day_of_year` - Day of year (1-365)
/// * `current_hour` - Current time in hours (0-24)
///
/// # Returns
///
/// LightingValuesDto with brightness, kelvin, RGB, and xy values.
LightingValuesDto calculateLighting(
        {required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear,
        required double currentHour}) =>
    RustLib.instance.api.crateApiCurveCalculateLighting(
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear,
        currentHour: currentHour);

/// Calculate step sequences for visualization.
///
/// This generates the step markers shown on the curve graph,
/// illustrating where each dim/brighten step would land.
/// Each point represents where pressing the step button would take you.
///
/// The step size is calculated as: (max_brightness - min_brightness) / max_steps
/// This matches the HTML/Python reference implementations.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `latitude` - Latitude in degrees
/// * `day_of_year` - Day of year (1-365)
/// * `start_hour` - Starting hour for step sequence
/// * `max_steps` - Number of steps from min to max brightness (determines step size)
///
/// # Returns
///
/// StepSequencesDto with step_up and step_down sequences.
StepSequencesDto calculateStepSequences(
        {required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear,
        required double startHour,
        required int maxSteps}) =>
    RustLib.instance.api.crateApiCurveCalculateStepSequences(
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear,
        startHour: startHour,
        maxSteps: maxSteps);

/// Get sun position at a specific hour.
///
/// Returns a value from -1 (solar midnight) to +1 (solar noon).
///
/// # Arguments
///
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `current_hour` - Current time in hours (0-24)
///
/// # Returns
///
/// Sun position value (-1 to +1).
double getSunPosition(
        {required double solarNoonHour, required double currentHour}) =>
    RustLib.instance.api.crateApiCurveGetSunPosition(
        solarNoonHour: solarNoonHour, currentHour: currentHour);

/// Check if the current hour is in the morning half.
///
/// # Arguments
///
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `current_hour` - Current time in hours (0-24)
///
/// # Returns
///
/// True if before solar noon, false otherwise.
bool isMorning({required double solarNoonHour, required double currentHour}) =>
    RustLib.instance.api.crateApiCurveIsMorning(
        solarNoonHour: solarNoonHour, currentHour: currentHour);

/// Calculate sunrise, sunset, and solar noon times for a location and date.
///
/// # Arguments
///
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York") or alias (e.g., "EST")
///
/// # Returns
///
/// SunTimesDto with sunrise, sunset, solar noon, and day length.
///
/// # Example
///
/// ```ignore
/// let times = get_sun_times(40.7128, -74.006, 2024, 6, 21, "America/New_York".to_string());
/// // times.sunrise ≈ 5.42 (5:25 AM)
/// // times.sunset ≈ 20.52 (8:31 PM)
/// ```
SunTimesDto getSunTimes(
        {required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGetSunTimes(
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);

/// Generate curve data with full solar information including sunrise/sunset.
///
/// This is an enhanced version of `generate_curve_data` that also calculates
/// sunrise and sunset times.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York")
///
/// # Returns
///
/// CurveDataDto with hourly values and full solar information.
CurveDataDto generateCurveDataWithSunTimes(
        {required CurveConfigDto config,
        required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGenerateCurveDataWithSunTimes(
        config: config,
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);

/// Calculate twilight times for a location and date.
///
/// Returns dawn (morning) and dusk (evening) times for:
/// - Civil twilight (6° below horizon)
/// - Nautical twilight (12° below horizon)
/// - Astronomical twilight (18° below horizon)
///
/// # Arguments
///
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York")
///
/// # Returns
///
/// TwilightTimesDto with dawn and dusk phases.
///
/// # Example
///
/// ```ignore
/// let twilight = get_twilight_times(40.7128, -74.006, 2024, 6, 21, "America/New_York".to_string());
/// // twilight.dawn.civil ≈ 4.87 (4:52 AM)
/// // twilight.dusk.civil ≈ 21.02 (9:01 PM)
/// ```
TwilightTimesDto getTwilightTimes(
        {required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGetTwilightTimes(
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);
