// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto/color.dart';
import 'dto/curve.dart';
import 'dto/solar.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_curve_data_dto`, `build_lighting_values_dto`, `resolve_curve_context`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ResolvedCurveContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Get sun position at a specific hour.
///
/// Returns a value from -1 (solar midnight) to +1 (solar noon).
///
/// # Arguments
///
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `current_hour` - Current time in hours (0-24)
///
/// # Returns
///
/// Sun position value (-1 to +1).
double getSunPosition(
        {required double solarNoonHour, required double currentHour}) =>
    RustLib.instance.api.crateApiCurveGetSunPosition(
        solarNoonHour: solarNoonHour, currentHour: currentHour);

/// Check if the current hour is in the morning half.
///
/// # Arguments
///
/// * `solar_noon_hour` - Hour of solar noon (0-24, local time)
/// * `current_hour` - Current time in hours (0-24)
///
/// # Returns
///
/// True if before solar noon, false otherwise.
bool isMorning({required double solarNoonHour, required double currentHour}) =>
    RustLib.instance.api.crateApiCurveIsMorning(
        solarNoonHour: solarNoonHour, currentHour: currentHour);

/// Calculate sunrise, sunset, and solar noon times for a location and date.
///
/// # Arguments
///
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York") or alias (e.g., "EST")
///
/// # Returns
///
/// SunTimesDto with sunrise, sunset, solar noon, and day length.
///
/// # Example
///
/// ```ignore
/// let times = get_sun_times(40.7128, -74.006, 2024, 6, 21, "America/New_York".to_string());
/// // times.sunrise ≈ 5.42 (5:25 AM)
/// // times.sunset ≈ 20.52 (8:31 PM)
/// ```
SunTimesDto getSunTimes(
        {required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGetSunTimes(
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);

/// Generate curve data with full solar information including sunrise/sunset.
///
/// This is the authoritative preview path for hourly sampling: it resolves
/// the same solar context the server preview endpoints use and samples once
/// per hour.
///
/// # Arguments
///
/// * `config` - Curve configuration parameters
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York")
///
/// # Returns
///
/// CurveDataDto with hourly values and full solar information.
CurveDataDto generateCurveDataWithSunTimes(
        {required CurveConfigDto config,
        required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGenerateCurveDataWithSunTimes(
        config: config,
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);

/// Generate high-resolution curve data using full solar context.
///
/// This matches the server preview semantics while allowing the caller to
/// choose the sampling density for live graph updates.
CurveDataDto generateCurveDataHighResWithSunTimes(
        {required CurveConfigDto config,
        required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone,
        required int samplesPerHour}) =>
    RustLib.instance.api.crateApiCurveGenerateCurveDataHighResWithSunTimes(
        config: config,
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone,
        samplesPerHour: samplesPerHour);

/// Calculate lighting values for a specific hour using full solar context.
LightingValuesDto calculateLightingWithSunTimes(
        {required CurveConfigDto config,
        required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone,
        required double currentHour}) =>
    RustLib.instance.api.crateApiCurveCalculateLightingWithSunTimes(
        config: config,
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone,
        currentHour: currentHour);

/// Calculate step sequences using full solar context.
StepSequencesDto calculateStepSequencesWithSunTimes(
        {required CurveConfigDto config,
        required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone,
        required double startHour,
        required int maxSteps}) =>
    RustLib.instance.api.crateApiCurveCalculateStepSequencesWithSunTimes(
        config: config,
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone,
        startHour: startHour,
        maxSteps: maxSteps);

/// Calculate twilight times for a location and date.
///
/// Returns dawn (morning) and dusk (evening) times for:
/// - Civil twilight (6° below horizon)
/// - Nautical twilight (12° below horizon)
/// - Astronomical twilight (18° below horizon)
///
/// # Arguments
///
/// * `latitude` - Latitude in degrees (positive = north)
/// * `longitude` - Longitude in degrees (negative = west)
/// * `year` - Full year (e.g., 2024)
/// * `month` - Month (1-12)
/// * `day` - Day of month (1-31)
/// * `timezone` - IANA timezone name (e.g., "America/New_York")
///
/// # Returns
///
/// TwilightTimesDto with dawn and dusk phases.
///
/// # Example
///
/// ```ignore
/// let twilight = get_twilight_times(40.7128, -74.006, 2024, 6, 21, "America/New_York".to_string());
/// // twilight.dawn.civil ≈ 4.87 (4:52 AM)
/// // twilight.dusk.civil ≈ 21.02 (9:01 PM)
/// ```
TwilightTimesDto getTwilightTimes(
        {required double latitude,
        required double longitude,
        required int year,
        required int month,
        required int day,
        required String timezone}) =>
    RustLib.instance.api.crateApiCurveGetTwilightTimes(
        latitude: latitude,
        longitude: longitude,
        year: year,
        month: month,
        day: day,
        timezone: timezone);
