// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the Philips Hue switch/button prefixes.
///
/// These prefixes identify Hue remote controls (switches and buttons).
///
/// # Returns
///
/// List of Hue switch/button prefixes
List<String> getHueSwitchPrefixes() =>
    RustLib.instance.api.crateApiHelpersGetHueSwitchPrefixes();

/// Get the Philips Hue OUI prefix.
///
/// This prefix identifies Philips Hue devices by their IEEE address.
///
/// # Returns
///
/// The Hue OUI prefix: "00:17:88:01:09"
String getHueOuiPrefix() =>
    RustLib.instance.api.crateApiHelpersGetHueOuiPrefix();

/// Get the Rhythm group prefix.
///
/// Groups created by Rhythm use this prefix.
///
/// # Returns
///
/// The Rhythm group prefix: "Rhythm_"
String getGroupPrefix() => RustLib.instance.api.crateApiHelpersGetGroupPrefix();

/// Normalize an IEEE address.
///
/// Converts to lowercase with colons between byte pairs.
/// Handles various input formats (with/without colons/hyphens).
///
/// # Arguments
///
/// * `ieee` - The IEEE address string to normalize
///
/// # Returns
///
/// The normalized IEEE address (lowercase, colon-separated)
///
/// # Example
///
/// ```ignore
/// let normalized = normalize_ieee("00:17:88:01:09:AB:CD:EF".to_string());
/// assert_eq!(normalized, "00:17:88:01:09:ab:cd:ef");
/// ```
String normalizeIeee({required String ieee}) =>
    RustLib.instance.api.crateApiHelpersNormalizeIeee(ieee: ieee);

/// Check if an IEEE address belongs to a Philips Hue device.
///
/// Detects Hue devices by checking if the IEEE address starts with
/// the Philips Hue OUI prefix (00:17:88:01:09).
///
/// # Arguments
///
/// * `ieee` - The IEEE address string to check
///
/// # Returns
///
/// True if this is a Hue device, false otherwise
///
/// # Example
///
/// ```ignore
/// assert!(is_hue_ieee("00:17:88:01:09:AB:CD:EF".to_string()));
/// assert!(!is_hue_ieee("00:11:22:33:44:55:66:77".to_string()));
/// ```
bool isHueIeee({required String ieee}) =>
    RustLib.instance.api.crateApiHelpersIsHueIeee(ieee: ieee);

/// Get the ZigBee endpoint for a manufacturer.
///
/// Different manufacturers use different ZigBee endpoints:
/// - Philips/Signify/Hue: endpoint 11
/// - IKEA: endpoint 1
/// - Others: endpoint 11 (default)
///
/// # Arguments
///
/// * `manufacturer` - The manufacturer name
/// * `model` - The model name
///
/// # Returns
///
/// The endpoint number to use (1 or 11)
///
/// # Example
///
/// ```ignore
/// assert_eq!(endpoint_for_manufacturer("Signify Netherlands B.V.".to_string(), "LCT015".to_string()), 11);
/// assert_eq!(endpoint_for_manufacturer("IKEA of Sweden".to_string(), "TRADFRI bulb".to_string()), 1);
/// ```
int endpointForManufacturer(
        {required String manufacturer, required String model}) =>
    RustLib.instance.api.crateApiHelpersEndpointForManufacturer(
        manufacturer: manufacturer, model: model);

/// Normalize an area ID for consistent comparison.
///
/// Converts to lowercase and replaces spaces/hyphens with underscores.
///
/// # Arguments
///
/// * `area_id` - The area ID to normalize
///
/// # Returns
///
/// The normalized area ID
///
/// # Example
///
/// ```ignore
/// assert_eq!(normalize_area_id("Living Room".to_string()), "living_room");
/// assert_eq!(normalize_area_id("living-room".to_string()), "living_room");
/// ```
String normalizeAreaId({required String areaId}) =>
    RustLib.instance.api.crateApiHelpersNormalizeAreaId(areaId: areaId);

/// Check if two area IDs match after normalization.
///
/// # Arguments
///
/// * `area_id_a` - First area ID
/// * `area_id_b` - Second area ID
///
/// # Returns
///
/// True if the normalized IDs match
///
/// # Example
///
/// ```ignore
/// assert!(area_ids_match("Living Room".to_string(), "living_room".to_string()));
/// assert!(!area_ids_match("living_room".to_string(), "bedroom".to_string()));
/// ```
bool areaIdsMatch({required String areaIdA, required String areaIdB}) =>
    RustLib.instance.api
        .crateApiHelpersAreaIdsMatch(areaIdA: areaIdA, areaIdB: areaIdB);

/// Generate a group name for an area.
///
/// Combines the Rhythm prefix with the area name, replacing spaces with underscores.
///
/// # Arguments
///
/// * `area_name` - The area name
///
/// # Returns
///
/// The group name (e.g., "Rhythm_Living_Room")
///
/// # Example
///
/// ```ignore
/// assert_eq!(group_name_for_area("Living Room".to_string()), "Rhythm_Living_Room");
/// ```
String groupNameForArea({required String areaName}) =>
    RustLib.instance.api.crateApiHelpersGroupNameForArea(areaName: areaName);

/// Check if an entity ID is a light entity.
///
/// # Arguments
///
/// * `entity_id` - The entity ID to check
///
/// # Returns
///
/// True if this is a light entity (starts with "light.")
///
/// # Example
///
/// ```ignore
/// assert!(is_light_entity("light.living_room".to_string()));
/// assert!(!is_light_entity("switch.living_room".to_string()));
/// ```
bool isLightEntity({required String entityId}) =>
    RustLib.instance.api.crateApiHelpersIsLightEntity(entityId: entityId);

/// Check if a group name is a Rhythm-managed group.
///
/// # Arguments
///
/// * `group_name` - The group name to check
///
/// # Returns
///
/// True if this is a Rhythm-managed group (starts with "Rhythm_")
///
/// # Example
///
/// ```ignore
/// assert!(is_rhythm_group("Rhythm_Living_Room".to_string()));
/// assert!(!is_rhythm_group("User_Group".to_string()));
/// ```
bool isRhythmGroup({required String groupName}) =>
    RustLib.instance.api.crateApiHelpersIsRhythmGroup(groupName: groupName);
