// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto/hue_registry.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `escape_json_string`, `find_matching_bracket`, `find_string_end`, `parse_behavior_mappings`, `parse_behavior_tracker_json`, `parse_string_array`, `parse_string_tuple`, `unescape_json_string`

/// Create a new empty behavior tracker.
///
/// # Example (Dart)
///
/// ```dart
/// final tracker = createBehaviorTracker();
/// ```
HueBehaviorTrackerDto createBehaviorTracker() =>
    RustLib.instance.api.crateApiHueRegistryCreateBehaviorTracker();

/// Add a behavior_instance to device mapping.
///
/// Returns a new tracker with the behavior added.
///
/// # Arguments
///
/// * `tracker` - Current tracker state
/// * `behavior_id` - The behavior_instance resource ID
/// * `device_id` - The device resource ID this behavior configures
///
/// # Example (Dart)
///
/// ```dart
/// tracker = behaviorTrackerAdd(
///   tracker: tracker,
///   behaviorId: "behavior-uuid",
///   deviceId: "device-uuid",
/// );
/// ```
HueBehaviorTrackerDto behaviorTrackerAdd(
        {required HueBehaviorTrackerDto tracker,
        required String behaviorId,
        required String deviceId}) =>
    RustLib.instance.api.crateApiHueRegistryBehaviorTrackerAdd(
        tracker: tracker, behaviorId: behaviorId, deviceId: deviceId);

/// Remove a behavior_instance.
///
/// Returns the new tracker state and whether a device was unconfigured.
///
/// # Arguments
///
/// * `tracker` - Current tracker state
/// * `behavior_id` - The behavior_instance resource ID that was deleted
///
/// # Example (Dart)
///
/// ```dart
/// final result = behaviorTrackerRemove(
///   tracker: tracker,
///   behaviorId: "behavior-uuid",
/// );
/// tracker = result.tracker;
/// if (result.deviceUnconfigured) {
///   print("Device is now available for Rhythm");
/// }
/// ```
BehaviorRemoveResultDto behaviorTrackerRemove(
        {required HueBehaviorTrackerDto tracker, required String behaviorId}) =>
    RustLib.instance.api.crateApiHueRegistryBehaviorTrackerRemove(
        tracker: tracker, behaviorId: behaviorId);

/// Check if a device is configured in the Hue app.
///
/// Returns `true` if the device has at least one behavior_instance,
/// meaning Hue handles its events and Rhythm should ignore them.
///
/// # Arguments
///
/// * `tracker` - Current tracker state
/// * `device_id` - The device resource ID to check
///
/// # Example (Dart)
///
/// ```dart
/// if (!behaviorTrackerIsConfigured(tracker: tracker, deviceId: deviceId)) {
///   // Process event with Rhythm
/// }
/// ```
bool behaviorTrackerIsConfigured(
        {required HueBehaviorTrackerDto tracker, required String deviceId}) =>
    RustLib.instance.api.crateApiHueRegistryBehaviorTrackerIsConfigured(
        tracker: tracker, deviceId: deviceId);

/// Get all configured device IDs.
///
/// # Arguments
///
/// * `tracker` - Current tracker state
///
/// # Example (Dart)
///
/// ```dart
/// final deviceIds = behaviorTrackerConfiguredDevices(tracker: tracker);
/// for (final id in deviceIds) {
///   print("Configured: $id");
/// }
/// ```
List<String> behaviorTrackerConfiguredDevices(
        {required HueBehaviorTrackerDto tracker}) =>
    RustLib.instance.api
        .crateApiHueRegistryBehaviorTrackerConfiguredDevices(tracker: tracker);

/// Get the number of tracked behaviors.
int behaviorTrackerBehaviorCount({required HueBehaviorTrackerDto tracker}) =>
    RustLib.instance.api
        .crateApiHueRegistryBehaviorTrackerBehaviorCount(tracker: tracker);

/// Get the number of configured devices.
int behaviorTrackerDeviceCount({required HueBehaviorTrackerDto tracker}) =>
    RustLib.instance.api
        .crateApiHueRegistryBehaviorTrackerDeviceCount(tracker: tracker);

/// Clear all tracked data.
///
/// Returns an empty tracker.
HueBehaviorTrackerDto behaviorTrackerClear(
        {required HueBehaviorTrackerDto tracker}) =>
    RustLib.instance.api
        .crateApiHueRegistryBehaviorTrackerClear(tracker: tracker);

/// Serialize behavior tracker to JSON string for persistence.
///
/// # Arguments
///
/// * `tracker` - Current tracker state
///
/// # Example (Dart)
///
/// ```dart
/// final json = behaviorTrackerToJson(tracker: tracker);
/// await prefs.setString('behavior_tracker', json);
/// ```
String behaviorTrackerToJson({required HueBehaviorTrackerDto tracker}) =>
    RustLib.instance.api
        .crateApiHueRegistryBehaviorTrackerToJson(tracker: tracker);

/// Deserialize behavior tracker from JSON string.
///
/// Returns None if the JSON is invalid.
///
/// # Arguments
///
/// * `json` - JSON string from `behavior_tracker_to_json`
///
/// # Example (Dart)
///
/// ```dart
/// final json = await prefs.getString('behavior_tracker');
/// if (json != null) {
///   final tracker = behaviorTrackerFromJson(json: json);
///   if (tracker != null) {
///     _behaviorTracker = tracker;
///   }
/// }
/// ```
HueBehaviorTrackerDto? behaviorTrackerFromJson({required String json}) =>
    RustLib.instance.api.crateApiHueRegistryBehaviorTrackerFromJson(json: json);

/// Create a new switch device DTO.
HueSwitchDeviceDto createSwitchDevice(
        {required String id,
        required String name,
        String? productName,
        required List<String> buttonIds,
        String? roomId}) =>
    RustLib.instance.api.crateApiHueRegistryCreateSwitchDevice(
        id: id,
        name: name,
        productName: productName,
        buttonIds: buttonIds,
        roomId: roomId);

/// Create a new button DTO.
HueButtonDto createButton(
        {required String id,
        required int controlId,
        required String ownerDeviceId}) =>
    RustLib.instance.api.crateApiHueRegistryCreateButton(
        id: id, controlId: controlId, ownerDeviceId: ownerDeviceId);

/// Create a new room DTO.
HueRoomDto createRoom({required String id, required String name}) =>
    RustLib.instance.api.crateApiHueRegistryCreateRoom(id: id, name: name);
