// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto/action.dart';
import 'dto/color.dart';
import 'dto/curve.dart';
import 'dto/runner.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Process an action and calculate the resulting lighting state.
///
/// Delegates to the shared `process_action` kernel in rhythm-core,
/// then converts the result to FFI-compatible DTOs.
ActionResultDto calculateActionResult(
        {required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear,
        required double currentHour,
        required RhythmActionDto action,
        required RoomStateDto roomState}) =>
    RustLib.instance.api.crateApiRunnerCalculateActionResult(
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear,
        currentHour: currentHour,
        action: action,
        roomState: roomState);

/// Create a new empty runner state.
RunnerStateDto createRunnerState() =>
    RustLib.instance.api.crateApiRunnerCreateRunnerState();

/// Add a room to the runner state.
RunnerStateDto runnerAddRoom(
        {required RunnerStateDto state, required RoomDto room}) =>
    RustLib.instance.api.crateApiRunnerRunnerAddRoom(state: state, room: room);

/// Remove a room from the runner state.
RunnerStateDto runnerRemoveRoom(
        {required RunnerStateDto state, required String roomId}) =>
    RustLib.instance.api
        .crateApiRunnerRunnerRemoveRoom(state: state, roomId: roomId);

/// Update device IDs for a room.
RunnerStateDto runnerSetRoomDevices(
        {required RunnerStateDto state,
        required String roomId,
        required List<String> deviceIds}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomDevices(
        state: state, roomId: roomId, deviceIds: deviceIds);

/// Handle an action for a specific room.
///
/// This is the main function for processing user actions. It takes the current
/// runner state, processes the action for the specified room, and returns
/// the new state along with commands to execute.
RunnerActionResultDto runnerHandleAction(
        {required RunnerStateDto state,
        required CurveConfigDto config,
        required double solarNoonHour,
        required double latitude,
        required int dayOfYear,
        required double currentHour,
        required String roomId,
        required RhythmActionDto action}) =>
    RustLib.instance.api.crateApiRunnerRunnerHandleAction(
        state: state,
        config: config,
        solarNoonHour: solarNoonHour,
        latitude: latitude,
        dayOfYear: dayOfYear,
        currentHour: currentHour,
        roomId: roomId,
        action: action);

/// Get a room by ID from the runner state.
RoomDto? runnerGetRoom(
        {required RunnerStateDto state, required String roomId}) =>
    RustLib.instance.api
        .crateApiRunnerRunnerGetRoom(state: state, roomId: roomId);

/// Get all room IDs from the runner state.
List<String> runnerGetRoomIds({required RunnerStateDto state}) =>
    RustLib.instance.api.crateApiRunnerRunnerGetRoomIds(state: state);

/// Get rooms that are not disabled (for kiosk mode).
///
/// Returns a copy of all rooms that have `disabled = false`.
List<RoomDto> runnerGetEnabledRooms({required RunnerStateDto state}) =>
    RustLib.instance.api.crateApiRunnerRunnerGetEnabledRooms(state: state);

/// Get rooms by source.
///
/// Returns a copy of all rooms with the specified source.
List<RoomDto> runnerGetRoomsBySource(
        {required RunnerStateDto state, required RoomSourceDto source}) =>
    RustLib.instance.api
        .crateApiRunnerRunnerGetRoomsBySource(state: state, source: source);

/// Set room disabled state.
///
/// Returns a new state with the room's disabled flag updated.
RunnerStateDto runnerSetRoomDisabled(
        {required RunnerStateDto state,
        required String roomId,
        required bool disabled}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomDisabled(
        state: state, roomId: roomId, disabled: disabled);

/// Set room lights_on state for syncing actual device state.
///
/// This is used to sync the Rust state with the actual light state
/// reported by external systems (e.g., Hue bridge).
///
/// Returns a new state with the room's lights_on flag updated.
RunnerStateDto runnerSetRoomLightsOn(
        {required RunnerStateDto state,
        required String roomId,
        required bool lightsOn}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomLightsOn(
        state: state, roomId: roomId, lightsOn: lightsOn);

/// Set room rhythm_enabled state.
///
/// Returns a new state with the room's rhythm_enabled flag updated.
RunnerStateDto runnerSetRoomRhythmEnabled(
        {required RunnerStateDto state,
        required String roomId,
        required bool rhythmEnabled}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomRhythmEnabled(
        state: state, roomId: roomId, rhythmEnabled: rhythmEnabled);

/// Set room time offset in minutes.
///
/// This is used to pin a room to a specific time position on the curve.
/// A positive offset moves forward in time (brighter in the morning),
/// a negative offset moves backward.
///
/// Returns a new state with the room's time_offset_minutes updated.
RunnerStateDto runnerSetRoomTimeOffset(
        {required RunnerStateDto state,
        required String roomId,
        required double timeOffsetMinutes}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomTimeOffset(
        state: state, roomId: roomId, timeOffsetMinutes: timeOffsetMinutes);

/// Set room brightness offset.
///
/// This is used to adjust a room's brightness relative to the curve.
/// A positive offset brightens, a negative offset dims.
///
/// Returns a new state with the room's brightness_offset updated.
RunnerStateDto runnerSetRoomBrightnessOffset(
        {required RunnerStateDto state,
        required String roomId,
        required double brightnessOffset}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomBrightnessOffset(
        state: state, roomId: roomId, brightnessOffset: brightnessOffset);

/// Set per-room curve config.
///
/// Pass `None` to use the global configuration.
/// Returns a new state with the room's curve_config updated.
RunnerStateDto runnerSetRoomCurveConfig(
        {required RunnerStateDto state,
        required String roomId,
        CurveConfigDto? config}) =>
    RustLib.instance.api.crateApiRunnerRunnerSetRoomCurveConfig(
        state: state, roomId: roomId, config: config);
