// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/curve.dart';
import 'api/dto/color.dart';
import 'api/dto/curve.dart';
import 'api/dto/hue.dart';
import 'api/dto/hue_registry.dart';
import 'api/dto/runner.dart';
import 'api/dto/solar.dart';
import 'api/helpers.dart';
import 'api/hue.dart';
import 'api/hue_registry.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BehaviorMappingDto dco_decode_behavior_mapping_dto(dynamic raw);

  @protected
  BehaviorRemoveResultDto dco_decode_behavior_remove_result_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CurveConfigDto dco_decode_box_autoadd_curve_config_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HueBehaviorTrackerDto dco_decode_box_autoadd_hue_behavior_tracker_dto(
      dynamic raw);

  @protected
  HueButtonEventTypeDto dco_decode_box_autoadd_hue_button_event_type_dto(
      dynamic raw);

  @protected
  RhythmActionDto dco_decode_box_autoadd_rhythm_action_dto(dynamic raw);

  @protected
  TwilightPhaseDto dco_decode_box_autoadd_twilight_phase_dto(dynamic raw);

  @protected
  CurveConfigDto dco_decode_curve_config_dto(dynamic raw);

  @protected
  CurveDataDto dco_decode_curve_data_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HueBehaviorTrackerDto dco_decode_hue_behavior_tracker_dto(dynamic raw);

  @protected
  HueButtonDto dco_decode_hue_button_dto(dynamic raw);

  @protected
  HueButtonEventTypeDto dco_decode_hue_button_event_type_dto(dynamic raw);

  @protected
  HueRoomDto dco_decode_hue_room_dto(dynamic raw);

  @protected
  HueSwitchDeviceDto dco_decode_hue_switch_device_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LightingValuesDto dco_decode_lighting_values_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BehaviorMappingDto> dco_decode_list_behavior_mapping_dto(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StepPointDto> dco_decode_list_step_point_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HueButtonEventTypeDto? dco_decode_opt_box_autoadd_hue_button_event_type_dto(
      dynamic raw);

  @protected
  RhythmActionDto? dco_decode_opt_box_autoadd_rhythm_action_dto(dynamic raw);

  @protected
  TwilightPhaseDto? dco_decode_opt_box_autoadd_twilight_phase_dto(dynamic raw);

  @protected
  RgbDto dco_decode_rgb_dto(dynamic raw);

  @protected
  RhythmActionDto dco_decode_rhythm_action_dto(dynamic raw);

  @protected
  SolarInfoDto dco_decode_solar_info_dto(dynamic raw);

  @protected
  StepPointDto dco_decode_step_point_dto(dynamic raw);

  @protected
  StepSequencesDto dco_decode_step_sequences_dto(dynamic raw);

  @protected
  SunTimesDto dco_decode_sun_times_dto(dynamic raw);

  @protected
  TwilightPhaseDto dco_decode_twilight_phase_dto(dynamic raw);

  @protected
  TwilightTimesDto dco_decode_twilight_times_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  XyDto dco_decode_xy_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BehaviorMappingDto sse_decode_behavior_mapping_dto(
      SseDeserializer deserializer);

  @protected
  BehaviorRemoveResultDto sse_decode_behavior_remove_result_dto(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CurveConfigDto sse_decode_box_autoadd_curve_config_dto(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HueBehaviorTrackerDto sse_decode_box_autoadd_hue_behavior_tracker_dto(
      SseDeserializer deserializer);

  @protected
  HueButtonEventTypeDto sse_decode_box_autoadd_hue_button_event_type_dto(
      SseDeserializer deserializer);

  @protected
  RhythmActionDto sse_decode_box_autoadd_rhythm_action_dto(
      SseDeserializer deserializer);

  @protected
  TwilightPhaseDto sse_decode_box_autoadd_twilight_phase_dto(
      SseDeserializer deserializer);

  @protected
  CurveConfigDto sse_decode_curve_config_dto(SseDeserializer deserializer);

  @protected
  CurveDataDto sse_decode_curve_data_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HueBehaviorTrackerDto sse_decode_hue_behavior_tracker_dto(
      SseDeserializer deserializer);

  @protected
  HueButtonDto sse_decode_hue_button_dto(SseDeserializer deserializer);

  @protected
  HueButtonEventTypeDto sse_decode_hue_button_event_type_dto(
      SseDeserializer deserializer);

  @protected
  HueRoomDto sse_decode_hue_room_dto(SseDeserializer deserializer);

  @protected
  HueSwitchDeviceDto sse_decode_hue_switch_device_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LightingValuesDto sse_decode_lighting_values_dto(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BehaviorMappingDto> sse_decode_list_behavior_mapping_dto(
      SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StepPointDto> sse_decode_list_step_point_dto(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HueButtonEventTypeDto? sse_decode_opt_box_autoadd_hue_button_event_type_dto(
      SseDeserializer deserializer);

  @protected
  RhythmActionDto? sse_decode_opt_box_autoadd_rhythm_action_dto(
      SseDeserializer deserializer);

  @protected
  TwilightPhaseDto? sse_decode_opt_box_autoadd_twilight_phase_dto(
      SseDeserializer deserializer);

  @protected
  RgbDto sse_decode_rgb_dto(SseDeserializer deserializer);

  @protected
  RhythmActionDto sse_decode_rhythm_action_dto(SseDeserializer deserializer);

  @protected
  SolarInfoDto sse_decode_solar_info_dto(SseDeserializer deserializer);

  @protected
  StepPointDto sse_decode_step_point_dto(SseDeserializer deserializer);

  @protected
  StepSequencesDto sse_decode_step_sequences_dto(SseDeserializer deserializer);

  @protected
  SunTimesDto sse_decode_sun_times_dto(SseDeserializer deserializer);

  @protected
  TwilightPhaseDto sse_decode_twilight_phase_dto(SseDeserializer deserializer);

  @protected
  TwilightTimesDto sse_decode_twilight_times_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  XyDto sse_decode_xy_dto(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_behavior_mapping_dto(BehaviorMappingDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.behaviorId), cst_encode_String(raw.deviceId)]
        .jsify()!;
  }

  @protected
  JSAny cst_encode_behavior_remove_result_dto(BehaviorRemoveResultDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_hue_behavior_tracker_dto(raw.tracker),
      cst_encode_bool(raw.deviceUnconfigured)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_curve_config_dto(CurveConfigDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_curve_config_dto(raw);
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_hue_behavior_tracker_dto(
      HueBehaviorTrackerDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_hue_behavior_tracker_dto(raw);
  }

  @protected
  int cst_encode_box_autoadd_hue_button_event_type_dto(
      HueButtonEventTypeDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_hue_button_event_type_dto(raw);
  }

  @protected
  int cst_encode_box_autoadd_rhythm_action_dto(RhythmActionDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_rhythm_action_dto(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_twilight_phase_dto(TwilightPhaseDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_twilight_phase_dto(raw);
  }

  @protected
  JSAny cst_encode_curve_config_dto(CurveConfigDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.minColorTemp),
      cst_encode_i_32(raw.maxColorTemp),
      cst_encode_i_32(raw.minBrightness),
      cst_encode_i_32(raw.maxBrightness),
      cst_encode_f_64(raw.widthLeftBri),
      cst_encode_f_64(raw.widthRightBri),
      cst_encode_f_64(raw.widthLeftCct),
      cst_encode_f_64(raw.widthRightCct),
      cst_encode_f_64(raw.shapeP),
      cst_encode_i_32(raw.maxDimSteps),
      cst_encode_i_32(raw.fadeMs),
      cst_encode_i_32(raw.motionTimeoutSecs)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_curve_data_dto(CurveDataDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_f_64_strict(raw.hours),
      cst_encode_list_prim_i_32_strict(raw.brightness),
      cst_encode_list_prim_i_32_strict(raw.kelvin),
      cst_encode_solar_info_dto(raw.solar)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_hue_behavior_tracker_dto(HueBehaviorTrackerDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_behavior_mapping_dto(raw.behaviorMappings),
      cst_encode_list_String(raw.configuredDeviceIds)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_hue_button_dto(HueButtonDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_u_8(raw.controlId),
      cst_encode_String(raw.ownerDeviceId)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_hue_room_dto(HueRoomDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.id), cst_encode_String(raw.name)].jsify()!;
  }

  @protected
  JSAny cst_encode_hue_switch_device_dto(HueSwitchDeviceDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_opt_String(raw.productName),
      cst_encode_list_String(raw.buttonIds),
      cst_encode_opt_String(raw.roomId)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_lighting_values_dto(LightingValuesDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.kelvin),
      cst_encode_i_32(raw.mireds),
      cst_encode_i_32(raw.brightness),
      cst_encode_rgb_dto(raw.rgb),
      cst_encode_xy_dto(raw.xy),
      cst_encode_f_64(raw.solarTime),
      cst_encode_f_64(raw.sunPosition)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_behavior_mapping_dto(List<BehaviorMappingDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_behavior_mapping_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_f_64_strict(Float64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_i_32_strict(Int32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_step_point_dto(List<StepPointDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_step_point_dto).toList().jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_hue_button_event_type_dto(
      HueButtonEventTypeDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_hue_button_event_type_dto(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_rhythm_action_dto(RhythmActionDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_rhythm_action_dto(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_twilight_phase_dto(TwilightPhaseDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_twilight_phase_dto(raw);
  }

  @protected
  JSAny cst_encode_rgb_dto(RgbDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_32(raw.r),
      cst_encode_i_32(raw.g),
      cst_encode_i_32(raw.b)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_solar_info_dto(SolarInfoDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_f_64(raw.sunrise),
      cst_encode_opt_box_autoadd_f_64(raw.sunset),
      cst_encode_f_64(raw.solarNoon),
      cst_encode_f_64(raw.solarMidnight),
      cst_encode_opt_box_autoadd_f_64(raw.dayLength),
      cst_encode_opt_box_autoadd_twilight_phase_dto(raw.dawn),
      cst_encode_opt_box_autoadd_twilight_phase_dto(raw.dusk)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_step_point_dto(StepPointDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_f_64(raw.hour),
      cst_encode_i_32(raw.brightness),
      cst_encode_i_32(raw.kelvin),
      cst_encode_list_prim_i_32_strict(raw.rgb)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_step_sequences_dto(StepSequencesDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_step_point_dto(raw.stepUp),
      cst_encode_list_step_point_dto(raw.stepDown)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_sun_times_dto(SunTimesDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_f_64(raw.sunrise),
      cst_encode_f_64(raw.sunset),
      cst_encode_f_64(raw.solarNoon),
      cst_encode_f_64(raw.solarMidnight),
      cst_encode_f_64(raw.dayLength)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_twilight_phase_dto(TwilightPhaseDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_f_64(raw.civil),
      cst_encode_opt_box_autoadd_f_64(raw.nautical),
      cst_encode_opt_box_autoadd_f_64(raw.astronomical)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_twilight_times_dto(TwilightTimesDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_twilight_phase_dto(raw.dawn),
      cst_encode_twilight_phase_dto(raw.dusk)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_xy_dto(XyDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_f_64(raw.x), cst_encode_f_64(raw.y)].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_hue_button_event_type_dto(HueButtonEventTypeDto raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_rhythm_action_dto(RhythmActionDto raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_behavior_mapping_dto(
      BehaviorMappingDto self, SseSerializer serializer);

  @protected
  void sse_encode_behavior_remove_result_dto(
      BehaviorRemoveResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_curve_config_dto(
      CurveConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hue_behavior_tracker_dto(
      HueBehaviorTrackerDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hue_button_event_type_dto(
      HueButtonEventTypeDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rhythm_action_dto(
      RhythmActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_twilight_phase_dto(
      TwilightPhaseDto self, SseSerializer serializer);

  @protected
  void sse_encode_curve_config_dto(
      CurveConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_curve_data_dto(CurveDataDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hue_behavior_tracker_dto(
      HueBehaviorTrackerDto self, SseSerializer serializer);

  @protected
  void sse_encode_hue_button_dto(HueButtonDto self, SseSerializer serializer);

  @protected
  void sse_encode_hue_button_event_type_dto(
      HueButtonEventTypeDto self, SseSerializer serializer);

  @protected
  void sse_encode_hue_room_dto(HueRoomDto self, SseSerializer serializer);

  @protected
  void sse_encode_hue_switch_device_dto(
      HueSwitchDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_lighting_values_dto(
      LightingValuesDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_behavior_mapping_dto(
      List<BehaviorMappingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_strict(
      Int32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_step_point_dto(
      List<StepPointDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_hue_button_event_type_dto(
      HueButtonEventTypeDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rhythm_action_dto(
      RhythmActionDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_twilight_phase_dto(
      TwilightPhaseDto? self, SseSerializer serializer);

  @protected
  void sse_encode_rgb_dto(RgbDto self, SseSerializer serializer);

  @protected
  void sse_encode_rhythm_action_dto(
      RhythmActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_solar_info_dto(SolarInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_step_point_dto(StepPointDto self, SseSerializer serializer);

  @protected
  void sse_encode_step_sequences_dto(
      StepSequencesDto self, SseSerializer serializer);

  @protected
  void sse_encode_sun_times_dto(SunTimesDto self, SseSerializer serializer);

  @protected
  void sse_encode_twilight_phase_dto(
      TwilightPhaseDto self, SseSerializer serializer);

  @protected
  void sse_encode_twilight_times_dto(
      TwilightTimesDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_xy_dto(XyDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__area_ids_match(
              String area_id_a, String area_id_b) =>
          wasmModule.wire__crate__api__helpers__area_ids_match(
              area_id_a, area_id_b);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_add(
              JSAny tracker, String behavior_id, String device_id) =>
          wasmModule.wire__crate__api__hue_registry__behavior_tracker_add(
              tracker, behavior_id, device_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_behavior_count(
              JSAny tracker) =>
          wasmModule
              .wire__crate__api__hue_registry__behavior_tracker_behavior_count(
                  tracker);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_clear(JSAny _tracker) =>
          wasmModule
              .wire__crate__api__hue_registry__behavior_tracker_clear(_tracker);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_configured_devices(
              JSAny tracker) =>
          wasmModule
              .wire__crate__api__hue_registry__behavior_tracker_configured_devices(
                  tracker);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_device_count(
              JSAny tracker) =>
          wasmModule
              .wire__crate__api__hue_registry__behavior_tracker_device_count(
                  tracker);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_is_configured(
              JSAny tracker, String device_id) =>
          wasmModule
              .wire__crate__api__hue_registry__behavior_tracker_is_configured(
                  tracker, device_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_remove(
              JSAny tracker, String behavior_id) =>
          wasmModule.wire__crate__api__hue_registry__behavior_tracker_remove(
              tracker, behavior_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__calculate_lighting_with_sun_times(
              JSAny config,
              double latitude,
              double longitude,
              int year,
              int month,
              int day,
              String timezone,
              double current_hour) =>
          wasmModule.wire__crate__api__curve__calculate_lighting_with_sun_times(
              config,
              latitude,
              longitude,
              year,
              month,
              day,
              timezone,
              current_hour);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__calculate_step_sequences_with_sun_times(
              JSAny config,
              double latitude,
              double longitude,
              int year,
              int month,
              int day,
              String timezone,
              double start_hour,
              int max_steps) =>
          wasmModule
              .wire__crate__api__curve__calculate_step_sequences_with_sun_times(
                  config,
                  latitude,
                  longitude,
                  year,
                  month,
                  day,
                  timezone,
                  start_hour,
                  max_steps);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_behavior_tracker() =>
          wasmModule.wire__crate__api__hue_registry__create_behavior_tracker();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_button(
              String id, int control_id, String owner_device_id) =>
          wasmModule.wire__crate__api__hue_registry__create_button(
              id, control_id, owner_device_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_room(String id, String name) =>
          wasmModule.wire__crate__api__hue_registry__create_room(id, name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_switch_device(
              String id,
              String name,
              String? product_name,
              JSAny button_ids,
              String? room_id) =>
          wasmModule.wire__crate__api__hue_registry__create_switch_device(
              id, name, product_name, button_ids, room_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__curve__curve_config_dto_default() =>
          wasmModule.wire__crate__api__dto__curve__curve_config_dto_default();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__endpoint_for_manufacturer(
              String manufacturer, String model) =>
          wasmModule.wire__crate__api__helpers__endpoint_for_manufacturer(
              manufacturer, model);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__generate_curve_data_high_res_with_sun_times(
              JSAny config,
              double latitude,
              double longitude,
              int year,
              int month,
              int day,
              String timezone,
              int samples_per_hour) =>
          wasmModule
              .wire__crate__api__curve__generate_curve_data_high_res_with_sun_times(
                  config,
                  latitude,
                  longitude,
                  year,
                  month,
                  day,
                  timezone,
                  samples_per_hour);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__generate_curve_data_with_sun_times(
              JSAny config,
              double latitude,
              double longitude,
              int year,
              int month,
              int day,
              String timezone) =>
          wasmModule
              .wire__crate__api__curve__generate_curve_data_with_sun_times(
                  config, latitude, longitude, year, month, day, timezone);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__get_group_prefix() =>
          wasmModule.wire__crate__api__helpers__get_group_prefix();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__get_hue_switch_prefixes() =>
          wasmModule.wire__crate__api__helpers__get_hue_switch_prefixes();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_sun_position(
              double solar_noon_hour, double current_hour) =>
          wasmModule.wire__crate__api__curve__get_sun_position(
              solar_noon_hour, current_hour);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_sun_times(double latitude, double longitude,
              int year, int month, int day, String timezone) =>
          wasmModule.wire__crate__api__curve__get_sun_times(
              latitude, longitude, year, month, day, timezone);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_twilight_times(
              double latitude,
              double longitude,
              int year,
              int month,
              int day,
              String timezone) =>
          wasmModule.wire__crate__api__curve__get_twilight_times(
              latitude, longitude, year, month, day, timezone);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__group_name_for_area(String area_name) =>
          wasmModule.wire__crate__api__helpers__group_name_for_area(area_name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__hue_registry__hue_behavior_tracker_dto_default() =>
          wasmModule
              .wire__crate__api__dto__hue_registry__hue_behavior_tracker_dto_default();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__hue__hue_button_event_type_dto_from_api_value(
              String value) =>
          wasmModule
              .wire__crate__api__dto__hue__hue_button_event_type_dto_from_api_value(
                  value);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_hue_ieee(String ieee) =>
          wasmModule.wire__crate__api__helpers__is_hue_ieee(ieee);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_light_entity(String entity_id) =>
          wasmModule.wire__crate__api__helpers__is_light_entity(entity_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__is_morning(
              double solar_noon_hour, double current_hour) =>
          wasmModule.wire__crate__api__curve__is_morning(
              solar_noon_hour, current_hour);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_rhythm_group(String group_name) =>
          wasmModule.wire__crate__api__helpers__is_rhythm_group(group_name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue__map_hue_button_event(
              int button_index, int event_type) =>
          wasmModule.wire__crate__api__hue__map_hue_button_event(
              button_index, event_type);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__normalize_area_id(String area_id) =>
          wasmModule.wire__crate__api__helpers__normalize_area_id(area_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__normalize_ieee(String ieee) =>
          wasmModule.wire__crate__api__helpers__normalize_ieee(ieee);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue__parse_hue_button_event_type(String api_value) =>
          wasmModule
              .wire__crate__api__hue__parse_hue_button_event_type(api_value);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__area_ids_match(
          String area_id_a, String area_id_b);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_add(
          JSAny tracker, String behavior_id, String device_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_behavior_count(
          JSAny tracker);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_clear(JSAny _tracker);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_configured_devices(
          JSAny tracker);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_device_count(
          JSAny tracker);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_is_configured(
          JSAny tracker, String device_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__behavior_tracker_remove(
          JSAny tracker, String behavior_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__calculate_lighting_with_sun_times(
          JSAny config,
          double latitude,
          double longitude,
          int year,
          int month,
          int day,
          String timezone,
          double current_hour);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__calculate_step_sequences_with_sun_times(
          JSAny config,
          double latitude,
          double longitude,
          int year,
          int month,
          int day,
          String timezone,
          double start_hour,
          int max_steps);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_behavior_tracker();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_button(
          String id, int control_id, String owner_device_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_room(String id, String name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue_registry__create_switch_device(String id,
          String name, String? product_name, JSAny button_ids, String? room_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__curve__curve_config_dto_default();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__endpoint_for_manufacturer(
          String manufacturer, String model);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__generate_curve_data_high_res_with_sun_times(
          JSAny config,
          double latitude,
          double longitude,
          int year,
          int month,
          int day,
          String timezone,
          int samples_per_hour);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__generate_curve_data_with_sun_times(
          JSAny config,
          double latitude,
          double longitude,
          int year,
          int month,
          int day,
          String timezone);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__get_group_prefix();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__get_hue_switch_prefixes();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_sun_position(
          double solar_noon_hour, double current_hour);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_sun_times(double latitude, double longitude,
          int year, int month, int day, String timezone);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__get_twilight_times(double latitude,
          double longitude, int year, int month, int day, String timezone);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__group_name_for_area(String area_name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__hue_registry__hue_behavior_tracker_dto_default();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__dto__hue__hue_button_event_type_dto_from_api_value(
          String value);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_hue_ieee(String ieee);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_light_entity(String entity_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__curve__is_morning(
          double solar_noon_hour, double current_hour);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__is_rhythm_group(String group_name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue__map_hue_button_event(
          int button_index, int event_type);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__normalize_area_id(String area_id);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__helpers__normalize_ieee(String ieee);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
      wire__crate__api__hue__parse_hue_button_event_type(String api_value);
}
