#!/usr/bin/env bash
set -euo pipefail
root=$(git rev-parse --show-toplevel)
ios="$root/app/flutter/rhythm_app/ios"
tmp=$(mktemp -d "${TMPDIR:-/tmp}/phone-matter-build.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
# Use the values generated by Flutter, including explicit --build-name/number
# overrides. Every extension configuration must package the same app version.
for configuration in Debug Release Profile; do
  if ! xcodebuild -project "$ios/Runner.xcodeproj" \
    -target MatterCommissioningExtension -configuration "$configuration" \
    -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO \
    CONFIGURATION_BUILD_DIR="$tmp/$configuration" build > "$tmp/build.log" 2>&1; then
    tail -80 "$tmp/build.log"
    exit 1
  fi
  python3 - "$ios/Flutter/Generated.xcconfig" \
    "$tmp/$configuration/MatterCommissioningExtension.appex/Info.plist" "$configuration" <<'PY'
import plistlib, sys
settings = dict(line.strip().split('=', 1) for line in open(sys.argv[1])
                if '=' in line and not line.startswith('//'))
with open(sys.argv[2], 'rb') as f:
    info = plistlib.load(f)
assert info['CFBundleVersion'] == settings['FLUTTER_BUILD_NUMBER']
assert info['CFBundleShortVersionString'] == settings['FLUTTER_BUILD_NAME']
assert info['NSAppTransportSecurity']['NSAllowsLocalNetworking'] is True
print(f"PASS: {sys.argv[3]} extension builds with Flutter version "
      f"{info['CFBundleShortVersionString']}+{info['CFBundleVersion']}")
PY
done
