#!/usr/bin/env bash
set -euo pipefail
root=$(git rev-parse --show-toplevel)
ios="$root/app/flutter/rhythm_app/ios"
tmp=$(mktemp -d "${TMPDIR:-/tmp}/phone-matter-build.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
# A standalone extension build is insufficient: Runner must build and embed it,
# and both processes must be allowed to open the same private request container.
python3 - "$ios" <<'PY'
import json, pathlib, plistlib, subprocess, sys
ios = pathlib.Path(sys.argv[1])
project = json.loads(subprocess.check_output([
    'plutil', '-convert', 'json', '-o', '-',
    str(ios / 'Runner.xcodeproj/project.pbxproj')
]))
objects = project['objects']
targets = {value.get('name'): (key, value) for key, value in objects.items()
           if value.get('isa') == 'PBXNativeTarget'}
extension_id, extension = targets['MatterCommissioningExtension']
_, runner = targets['Runner']
assert any(objects[key].get('target') == extension_id
           for key in runner['dependencies']), 'Runner must build its Matter extension'
assert any(
    str(objects[key].get('dstSubfolderSpec')) == '13' and any(
        objects[file]['fileRef'] == extension['productReference']
        for file in objects[key].get('files', []))
    for key in runner['buildPhases']
), 'Runner must embed the Matter extension in PlugIns'
group = 'group.lighting.rhythm.app.matter'
for relative in ['Runner/Runner.entitlements',
                 'MatterCommissioningExtension/MatterCommissioningExtension.entitlements']:
    with (ios / relative).open('rb') as source:
        entitlements = plistlib.load(source)
    assert group in entitlements['com.apple.security.application-groups']
print('PASS: app/extension dependency, embedding and shared request-container entitlement')
PY
# Use the values generated by Flutter, including explicit --build-name/number
# overrides. Every extension configuration must package the same app version.
for configuration in Debug Release Profile; do
  if ! xcodebuild -project "$ios/Runner.xcodeproj" \
    -target MatterCommissioningExtension -configuration "$configuration" \
    -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO \
    CONFIGURATION_BUILD_DIR="$tmp/$configuration" build > "$tmp/build.log" 2>&1; then
    tail -80 "$tmp/build.log"
    exit 1
  fi
  python3 - "$ios/Flutter/Generated.xcconfig" \
    "$tmp/$configuration/MatterCommissioningExtension.appex/Info.plist" "$configuration" <<'PY'
import plistlib, sys
settings = dict(line.strip().split('=', 1) for line in open(sys.argv[1])
                if '=' in line and not line.startswith('//'))
with open(sys.argv[2], 'rb') as f:
    info = plistlib.load(f)
assert info['CFBundleVersion'] == settings['FLUTTER_BUILD_NUMBER']
assert info['CFBundleShortVersionString'] == settings['FLUTTER_BUILD_NAME']
assert info['NSAppTransportSecurity']['NSAllowsLocalNetworking'] is True
print(f"PASS: {sys.argv[3]} extension builds with Flutter version "
      f"{info['CFBundleShortVersionString']}+{info['CFBundleVersion']}")
PY
done
